rm -f test\bh.10.dat
rm -f test\bh.dat
rm -f test\bonf.10.dat
rm -f test\bonf.dat
rm -f test\dfdr.10.dat
rm -f test\dfdr.dat
rm -f test\gbh.10.dat
rm -f test\gbh.dat
rm -f test\noadj.10.dat
rm -f test\noadj.dat
rm -f test\ssbh.10.dat
rm -f test\ssbh.dat
